on:
  push:
    branches:
      - "feature/*"

name: ğŸ§ª NasazenÃ­ feature na testovacÃ­ prostÅ™edÃ­

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ StaÅ¾enÃ­ aktuÃ¡lnÃ­ho kÃ³du
        uses: actions/checkout@v3

      - name: ğŸ›« Instalace zÃ¡vislostÃ­
        run: yarn install

      - name: ğŸ“¦ SestavenÃ­ aplikace
        run: yarn build

      - name: â© Merge do testu
        run: |
          AUTHOR_NAME=$(git log -1 --pretty=format:'%an')
          AUTHOR_EMAIL=$(git log -1 --pretty=format:'%ae')
          git fetch origin
          git checkout test
          git config user.name "$AUTHOR_NAME"
          git config user.email "$AUTHOR_EMAIL"
          git merge --no-ff "${{ github.ref }}" --allow-unrelated-histories
          git push origin test
